DROP DATABASE IF EXISTS matching;
CREATE DATABASE matching;

/c matching;

DROP TYPE IF EXISTS "user_type";
DROP TYPE IF EXISTS "csap_track_type";
DROP TYPE IF EXISTS "preference_type";
DROP TYPE IF EXISTS "gender_type";
DROP TYPE IF EXISTS "priority_column_type";

DROP TABLE IF EXISTS "mentee";
DROP TABLE IF EXISTS "profile";
DROP TABLE IF EXISTS "users";
DROP TABLE IF EXISTS "roles";
DROP TABLE IF EXISTS "cities";
DROP TABLE IF EXISTS "countries";
DROP TABLE IF EXISTS "theatres";

CREATE TYPE "user_type" AS ENUM (
  'mentor',
  'mentee'
);

CREATE TYPE "csap_track_type" AS ENUM (
  'engineer',
  'sales'
);

CREATE TYPE "preference_type" AS ENUM (
  'yes',
  'no',
  'no_preference'
);

CREATE TYPE "gender_type" AS ENUM (
  'male',
  'female',
  'other'
);

CREATE TYPE "priority_column_type" AS ENUM (
  'role',
  'strengths',
  'gender',
  'theater',
  'none'
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar,
  "password_hash" varchar,
  "type" user_type
);

CREATE TABLE "mentee_mentors" (
  "mentee_user_id" int,
  "mentor_user_id" int,
  "room_id" varchar
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "cities" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "countries" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "theatres" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "strengths" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "interests" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "titles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "profiles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "role_id" int,
  "title_id" int,
  "gender" gender_type,
  "city_id" int,
  "country_id" int,
  "theatre_id" int,
  "bio" text,
  "csap_track" csap_track_type,
  "same_theatre" preference_type,
  "same_gender" preference_type,
  "same_role" preference_type,
  "first_priority" priority_column_type,
  "second_priority" priority_column_type
);

CREATE TABLE "profile_strengths" (
  "profile_id" int,
  "strength_id" int
);

CREATE TABLE "profile_interests" (
  "profile_id" int,
  "interest_id" int
);

ALTER TABLE "mentee" ADD FOREIGN KEY ("mentee_user_id") REFERENCES "users" ("id");

ALTER TABLE "mentee" ADD FOREIGN KEY ("mentor_user_id") REFERENCES "users" ("id");

ALTER TABLE "profile" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "profile" ADD FOREIGN KEY ("title_id") REFERENCES "titles" ("id");

ALTER TABLE "profile" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "profile" ADD FOREIGN KEY ("city_id") REFERENCES "cities" ("id");

ALTER TABLE "profile" ADD FOREIGN KEY ("country_id") REFERENCES "countries" ("id");

ALTER TABLE "profile" ADD FOREIGN KEY ("theatre_id") REFERENCES "theatres" ("id");

ALTER TABLE "profile_strengths" ADD FOREIGN KEY ("profile_id") REFERENCES "profiles" ("id");

ALTER TABLE "profile_strengths" ADD FOREIGN KEY ("strength_id") REFERENCES "strengths" ("id");

ALTER TABLE "profile_interests" ADD FOREIGN KEY ("profile_id") REFERENCES "profiles" ("id");

ALTER TABLE "profile_interests" ADD FOREIGN KEY ("interest_id") REFERENCES "interests" ("id");
